//! Native gRPC client support for Godot 4.6+, as a Rust GDExtension built on
//! [godot-rust (gdext)](https://github.com/godot-rust/gdext),
//! [tonic](https://github.com/hyperium/tonic), and [tokio](https://tokio.rs).
//!
//! This crate is consumed **from GDScript**, not as a Rust API: it registers
//! Godot classes (rather than exposing public Rust items), so this rustdoc page
//! is intentionally sparse. For usage, see the
//! [guide](https://quobox.github.io/godot-grpc/).
//!
//! # Registered Godot classes
//! - `GrpcChannel` — connect over TCP (`http://…`) or a Unix socket (`unix://…`);
//!   start unary/server-/client-/bidi calls (tier 1: raw `PackedByteArray`s).
//! - `GrpcCall` — one in-flight RPC; signals `completed` / `stream_item` /
//!   `failed` / `cancelled` and the unified `finished`; `cancel()`.
//! - `GrpcStatus` / `GrpcError` — the error model.
//! - `GrpcRuntime` — the Tokio runtime singleton.
//! - With the `tier2` feature: `GrpcDescriptorPool`, `GrpcServiceStub`,
//!   `GrpcMessage` — the runtime descriptor API (`Dictionary`/`GrpcMessage`,
//!   no codegen). Typed GDScript clients are generated by the companion
//!   `protoc-gen-godot-grpc` plugin.
//!
//! # Threading
//! tokio runs on a background thread; results are marshalled to the Godot main
//! thread over a crossbeam channel, so `Gd<T>` is never shared across threads.
//!
//! # Features
//! `default = ["client", "uds", "tier1"]`. `tier2` adds the descriptor API
//! (pulls in `prost-reflect`); kept out of the default to keep kiosk builds small.

// With tier 2 off, the call-setup descriptor params degrade to `()`, so passing
// them trips clippy's unit_arg lint; harmless and only in tier1-only builds.
#![cfg_attr(not(feature = "tier2"), allow(clippy::unit_arg))]

use godot::prelude::*;

mod bridge;
mod call;
mod channel;
mod error;
mod runtime;
mod transport;

// Tier 2 — runtime descriptor API (Dictionary/GrpcMessage). Off by default.
#[cfg(feature = "tier2")]
mod convert;
#[cfg(feature = "tier2")]
mod descriptor;
#[cfg(feature = "tier2")]
mod message;
#[cfg(feature = "tier2")]
mod service;

#[cfg(test)]
mod tests;

struct GodotGrpc;

#[gdextension]
unsafe impl ExtensionLibrary for GodotGrpc {
    // Start the Tokio runtime once Godot is fully initialized, tear it down
    // before shutdown. `MainLoop` is the fully-initialized stage (Godot 4.5+);
    // all classes are still available at the matching deinit.
    fn on_stage_init(stage: InitStage) {
        if stage == InitStage::MainLoop {
            runtime::start(2);
        }
    }

    fn on_stage_deinit(stage: InitStage) {
        if stage == InitStage::MainLoop {
            runtime::shutdown();
        }
    }

    // Per-frame main-thread pump: drain Tokio→Godot events and emit signals.
    // Runs after all Node `process()` methods (see bridge.rs for why this
    // replaces the spec's per-tree `_GrpcPump` Node).
    fn on_main_loop_frame() {
        bridge::drain();
    }
}
