//! Codegen: turn a `CodeGeneratorRequest` into typed GDScript.
//!
//! For each requested `.proto` file we emit `<stem>_messages.gd` (typed message
//! classes extending `GrpcMessage`, with that file's transitive descriptor
//! closure embedded as base64 so it is self-contained) and `<stem>_<service>.gd`
//! (a typed stub over `GrpcServiceStub`). Other `proto_file`s are loaded into
//! the pool for type resolution but not emitted.

use std::collections::BTreeSet;

use base64::Engine;
use heck::{ToPascalCase, ToSnakeCase};
use prost::Message;
use prost_reflect::{
    DescriptorPool, FieldDescriptor, FileDescriptor, Kind, MessageDescriptor, ServiceDescriptor,
};
use prost_types::FileDescriptorSet;
use prost_types::compiler::{CodeGeneratorRequest, CodeGeneratorResponse, code_generator_response};

/// Generate GDScript for every file in `request.file_to_generate`.
pub fn generate(request: CodeGeneratorRequest) -> CodeGeneratorResponse {
    let mut pool = DescriptorPool::new();
    if let Err(e) = pool.add_file_descriptor_protos(request.proto_file.iter().cloned()) {
        return CodeGeneratorResponse {
            error: Some(format!("failed to build descriptor pool: {e}")),
            ..Default::default()
        };
    }

    let mut files = Vec::new();
    for proto_name in &request.file_to_generate {
        let Some(file) = pool.get_file_by_name(proto_name) else {
            continue;
        };
        let stem = file_stem(proto_name);
        let messages_class = messages_class_for(&file);

        // Embed only this file's transitive descriptor closure, not the whole
        // request — avoids duplicating unrelated files across outputs.
        let desc_b64 = encode_closure(&file, &request.proto_file);

        // Always emit the messages file: it hosts the cached pool() the service
        // stub needs, even for a file that only defines services.
        let messages: Vec<MessageDescriptor> = file.messages().collect();
        files.push(out(
            format!("{stem}_messages.gd"),
            gen_messages(&messages_class, &messages, &desc_b64),
        ));
        for service in file.services() {
            files.push(out(
                format!("{stem}_{}.gd", service.name().to_snake_case()),
                gen_service(&service, &messages_class),
            ));
        }
    }

    CodeGeneratorResponse {
        supported_features: Some(code_generator_response::Feature::Proto3Optional as u64),
        file: files,
        ..Default::default()
    }
}

fn out(name: String, content: String) -> code_generator_response::File {
    code_generator_response::File {
        name: Some(name),
        content: Some(content),
        ..Default::default()
    }
}

/// `"foo/bar.proto"` -> `"bar"` (strips the suffix once, unlike `trim_end_matches`).
fn file_stem(proto: &str) -> String {
    let base = proto.rsplit('/').next().unwrap_or(proto);
    base.strip_suffix(".proto").unwrap_or(base).to_string()
}

/// The `*_messages.gd` `class_name` for the file that defines `file`.
fn messages_class_for(file: &FileDescriptor) -> String {
    format!("{}Messages", file_stem(file.name()).to_pascal_case())
}

/// The messages class that defines a given message type (may be an import).
fn message_owner_class(md: &MessageDescriptor) -> String {
    messages_class_for(&md.parent_file())
}

/// Base64 of a `FileDescriptorSet` containing `file` + its transitive imports,
/// in the request's (topological) order so the runtime pool resolves cleanly.
fn encode_closure(file: &FileDescriptor, all: &[prost_types::FileDescriptorProto]) -> String {
    let mut needed = BTreeSet::new();
    collect_deps(file, &mut needed);
    let set = FileDescriptorSet {
        file: all
            .iter()
            .filter(|f| f.name.as_deref().is_some_and(|n| needed.contains(n)))
            .cloned()
            .collect(),
    };
    base64::engine::general_purpose::STANDARD.encode(set.encode_to_vec())
}

fn collect_deps(file: &FileDescriptor, acc: &mut BTreeSet<String>) {
    if !acc.insert(file.name().to_string()) {
        return;
    }
    for dep in file.dependencies() {
        collect_deps(&dep, acc);
    }
}

const HEADER: &str = "## Auto-generated by protoc-gen-godot-grpc. DO NOT EDIT.\n";

fn gen_messages(class_name: &str, messages: &[MessageDescriptor], desc_b64: &str) -> String {
    let mut s = String::new();
    s.push_str(HEADER);
    s.push_str(&format!("class_name {class_name}\n\n"));
    s.push_str("static var _pool: GrpcDescriptorPool\n\n");
    s.push_str("static func pool() -> GrpcDescriptorPool:\n");
    s.push_str("\tif _pool == null:\n");
    s.push_str("\t\t_pool = GrpcDescriptorPool.new()\n");
    s.push_str("\t\t_pool.load_bytes(Marshalls.base64_to_raw(_DESCRIPTOR_B64))\n");
    s.push_str("\treturn _pool\n\n");
    s.push_str(&format!("const _DESCRIPTOR_B64 := \"{desc_b64}\"\n\n"));
    for m in messages {
        s.push_str(&gen_message_class(class_name, m));
        s.push('\n');
    }
    s
}

fn gen_message_class(outer: &str, m: &MessageDescriptor) -> String {
    let name = m.name();
    let mut s = String::new();
    s.push_str(&format!("class {name} extends GrpcMessage:\n"));
    s.push_str("\tfunc _init() -> void:\n");
    s.push_str(&format!(
        "\t\tbind_type({outer}.pool(), \"{}\")\n",
        m.full_name()
    ));
    s.push_str(&format!(
        "\tstatic func wrap(m: GrpcMessage) -> {outer}.{name}:\n"
    ));
    s.push_str(&format!("\t\tvar r := {outer}.{name}.new()\n"));
    s.push_str("\t\tr.adopt(m)\n");
    s.push_str("\t\treturn r\n");
    for field in m.fields() {
        let prop = sanitize_ident(field.name());
        s.push_str(&format!("\tvar {prop}: {}:\n", gdscript_type(&field)));
        s.push_str(&format!(
            "\t\tget: return get_field(\"{}\")\n",
            field.name()
        ));
        s.push_str(&format!("\t\tset(v): set_field(\"{}\", v)\n", field.name()));
    }
    s
}

fn gdscript_type(field: &FieldDescriptor) -> &'static str {
    if field.is_map() {
        return "Dictionary";
    }
    if field.is_list() {
        return "Array";
    }
    match field.kind() {
        Kind::Double | Kind::Float => "float",
        Kind::Int32
        | Kind::Int64
        | Kind::Uint32
        | Kind::Uint64
        | Kind::Sint32
        | Kind::Sint64
        | Kind::Fixed32
        | Kind::Fixed64
        | Kind::Sfixed32
        | Kind::Sfixed64
        | Kind::Enum(_) => "int",
        Kind::Bool => "bool",
        Kind::String => "String",
        Kind::Bytes => "PackedByteArray",
        Kind::Message(_) => "GrpcMessage",
    }
}

fn gen_service(service: &ServiceDescriptor, messages_class: &str) -> String {
    let pascal = file_stem(service.parent_file().name()).to_pascal_case();
    let svc_class = format!("{pascal}{}", service.name().to_pascal_case());
    let mut s = String::new();
    s.push_str(HEADER);
    s.push_str(&format!("class_name {svc_class}\n\n"));
    s.push_str("var _stub: GrpcServiceStub\n\n");
    s.push_str("func _init(channel: GrpcChannel) -> void:\n");
    s.push_str(&format!(
        "\t_stub = {messages_class}.pool().service(\"{}\").client(channel)\n\n",
        service.full_name()
    ));

    for m in service.methods() {
        let fn_name = sanitize_ident(&m.name().to_snake_case());
        let rpc = m.name();
        // Qualify by the *defining* file's messages class (may be an import).
        let input = format!("{}.{}", message_owner_class(&m.input()), m.input().name());
        let output = format!("{}.{}", message_owner_class(&m.output()), m.output().name());
        match (m.is_client_streaming(), m.is_server_streaming()) {
            (false, false) => {
                // Unary: await the unified terminal signal. `finished` carries the
                // response on success or null on failure, so this never hangs.
                s.push_str(&format!("func {fn_name}(request: {input}) -> {output}:\n"));
                s.push_str(&format!(
                    "\tvar call := _stub.unary(\"{rpc}\", request.to_dict())\n"
                ));
                s.push_str("\tif call == null:\n");
                s.push_str("\t\treturn null\n");
                s.push_str(&format!(
                    "\tcall.failed.connect(func(status): push_error(\"{rpc} failed: \" + status.message()))\n"
                ));
                s.push_str("\tvar result = await call.finished\n");
                s.push_str("\tif result == null:\n");
                s.push_str("\t\treturn null\n");
                s.push_str(&format!("\treturn {output}.wrap(result)\n\n"));
            }
            (false, true) => {
                // Server streaming: returns the call; wrap items with {output}.wrap().
                s.push_str(&format!("func {fn_name}(request: {input}) -> GrpcCall:\n"));
                s.push_str(&format!(
                    "\treturn _stub.server_stream(\"{rpc}\", request.to_dict())\n\n"
                ));
            }
            (true, false) => {
                // Client streaming: send with call.send_dict(), finish with close_send().
                s.push_str(&format!("func {fn_name}() -> GrpcCall:\n"));
                s.push_str(&format!("\treturn _stub.client_stream(\"{rpc}\")\n\n"));
            }
            (true, true) => {
                // Bidirectional.
                s.push_str(&format!("func {fn_name}() -> GrpcCall:\n"));
                s.push_str(&format!("\treturn _stub.bidi(\"{rpc}\")\n\n"));
            }
        }
    }
    s
}

/// Suffix a `_` if the proto identifier would collide with a GDScript keyword or
/// an inherited `GrpcMessage`/`GrpcCall` member, keeping generated code valid.
/// The wire/field name (passed to `get_field`/`unary`) is unaffected.
fn sanitize_ident(name: &str) -> String {
    const RESERVED: &[&str] = &[
        // GDScript keywords / literals
        "if",
        "elif",
        "else",
        "for",
        "while",
        "match",
        "break",
        "continue",
        "pass",
        "return",
        "class",
        "class_name",
        "extends",
        "is",
        "in",
        "as",
        "self",
        "super",
        "func",
        "static",
        "const",
        "enum",
        "var",
        "breakpoint",
        "preload",
        "await",
        "yield",
        "signal",
        "assert",
        "void",
        "and",
        "or",
        "not",
        "true",
        "false",
        "null",
        "INF",
        "NAN",
        "PI",
        "TAU",
        // members we generate / inherit and don't want shadowed
        "get_field",
        "set_field",
        "has_field",
        "to_dict",
        "type_name",
        "bind_type",
        "adopt",
        "send",
        "send_dict",
        "close_send",
        "cancel",
        "wrap",
        "pool",
    ];
    if RESERVED.contains(&name) {
        format!("{name}_")
    } else {
        name.to_string()
    }
}
